-- Populate database with realistic infrastructure news for 6 cities

-- Bengaluru News
INSERT INTO local_news (id, headline, url, source, snippet, is_tragic, city, location, published_at, confidence_score) VALUES
(gen_random_uuid(), 'Namma Metro Phase 3 work begins on Outer Ring Road corridor', 'https://example.com/bengaluru-metro-phase3', 'The Hindu', 'BMRCL announces commencement of construction for the 32km Phase 3 corridor connecting key tech hubs along Outer Ring Road', false, 'bengaluru', ST_SetSRID(ST_MakePoint(77.5946, 12.9716), 4326), NOW() - INTERVAL '2 hours', 85),
(gen_random_uuid(), 'Pothole crisis: BBMP identifies 2,847 damaged roads across city', 'https://example.com/bengaluru-potholes', 'Deccan Herald', 'Civic body releases ward-wise data showing Mahadevapura zone worst affected with 487 pothole complaints in past month', true, 'bengaluru', ST_SetSRID(ST_MakePoint(77.6946, 12.9916), 4326), NOW() - INTERVAL '5 hours', 78),
(gen_random_uuid(), 'Bellandur Lake cleanup enters final phase, says KSPCB', 'https://example.com/bellandur-cleanup', 'Times of India', 'State pollution board reports 60% reduction in foam formation after installation of sewage treatment plants', false, 'bengaluru', ST_SetSRID(ST_MakePoint(77.6761, 12.9260), 4326), NOW() - INTERVAL '8 hours', 82),
(gen_random_uuid(), 'Electronic City flyover project delayed by 6 months', 'https://example.com/ecity-flyover-delay', 'The Hindu', 'NHAI cites land acquisition issues for postponement of Rs 450 crore elevated corridor project', true, 'bengaluru', ST_SetSRID(ST_MakePoint(77.6648, 12.8456), 4326), NOW() - INTERVAL '12 hours', 75),
(gen_random_uuid(), 'Whitefield residents protest against unauthorized construction', 'https://example.com/whitefield-protest', 'Bangalore Mirror', 'Local RWAs file complaint with BDA over 15-storey building violating zoning regulations', true, 'bengaluru', ST_SetSRID(ST_MakePoint(77.7499, 12.9698), 4326), NOW() - INTERVAL '1 day', 80);

-- Mumbai News
INSERT INTO local_news (id, headline, url, source, snippet, is_tragic, city, location, published_at, confidence_score) VALUES
(gen_random_uuid(), 'Mumbai Metro Line 3 achieves 95% completion milestone', 'https://example.com/mumbai-metro-line3', 'Mumbai Mirror', 'MMRCL announces trial runs to begin next month on 33.5km underground corridor from Colaba to SEEPZ', false, 'mumbai', ST_SetSRID(ST_MakePoint(72.8777, 19.0760), 4326), NOW() - INTERVAL '3 hours', 88),
(gen_random_uuid(), 'BMC identifies 127 dangerous buildings in island city', 'https://example.com/mumbai-dangerous-buildings', 'Indian Express', 'Civic body issues evacuation notices to residents of dilapidated structures in Girgaon and Kalbadevi areas', true, 'mumbai', ST_SetSRID(ST_MakePoint(72.8311, 18.9520), 4326), NOW() - INTERVAL '6 hours', 83),
(gen_random_uuid(), 'Coastal Road project opens new 5km stretch in Worli', 'https://example.com/coastal-road-worli', 'Times of India', 'Rs 12,000 crore infrastructure project reduces travel time between South Mumbai and Western suburbs by 30 minutes', false, 'mumbai', ST_SetSRID(ST_MakePoint(72.8181, 19.0176), 4326), NOW() - INTERVAL '10 hours', 86),
(gen_random_uuid(), 'Waterlogging in Andheri subway disrupts traffic for 4 hours', 'https://example.com/andheri-waterlogging', 'Hindustan Times', 'Heavy rainfall overwhelms drainage system, BMC deploys pumps to clear water accumulation', true, 'mumbai', ST_SetSRID(ST_MakePoint(72.8697, 19.1136), 4326), NOW() - INTERVAL '18 hours', 77),
(gen_random_uuid(), 'Bandra-Versova Sea Link receives environmental clearance', 'https://example.com/bandra-versova-sealink', 'Mumbai Mirror', 'MSRDC gets green signal for Rs 8,000 crore project connecting western suburbs', false, 'mumbai', ST_SetSRID(ST_MakePoint(72.8263, 19.0596), 4326), NOW() - INTERVAL '1 day', 84);

-- Delhi News
INSERT INTO local_news (id, headline, url, source, snippet, is_tragic, city, location, published_at, confidence_score) VALUES
(gen_random_uuid(), 'Delhi Metro extends Pink Line to Maujpur with 3 new stations', 'https://example.com/delhi-metro-pink-extension', 'The Hindu', 'DMRC inaugurates 7.5km extension improving connectivity to Northeast Delhi neighborhoods', false, 'delhi', ST_SetSRID(ST_MakePoint(77.2090, 28.7041), 4326), NOW() - INTERVAL '4 hours', 87),
(gen_random_uuid(), 'Air quality deteriorates to severe category in 12 monitoring stations', 'https://example.com/delhi-air-quality', 'Indian Express', 'CPCB data shows AQI crossing 400 mark in Anand Vihar, Rohini and Dwarka areas', true, 'delhi', ST_SetSRID(ST_MakePoint(77.3178, 28.6469), 4326), NOW() - INTERVAL '7 hours', 81),
(gen_random_uuid(), 'PWD completes resurfacing of 45km roads in South Delhi', 'https://example.com/delhi-road-resurfacing', 'Times of India', 'Department spends Rs 120 crore on infrastructure upgrade covering Hauz Khas, Saket and Vasant Vihar', false, 'delhi', ST_SetSRID(ST_MakePoint(77.2167, 28.5494), 4326), NOW() - INTERVAL '11 hours', 79),
(gen_random_uuid(), 'Yamuna water level rises above danger mark at ITO barrage', 'https://example.com/yamuna-flood-warning', 'Hindustan Times', 'Irrigation department issues flood alert for low-lying areas along river banks', true, 'delhi', ST_SetSRID(ST_MakePoint(77.2500, 28.6289), 4326), NOW() - INTERVAL '15 hours', 76),
(gen_random_uuid(), 'Dwarka Expressway toll plaza becomes operational', 'https://example.com/dwarka-expressway-toll', 'Economic Times', 'NHAI begins toll collection on 29km expressway connecting Delhi to Gurugram', false, 'delhi', ST_SetSRID(ST_MakePoint(77.0460, 28.5921), 4326), NOW() - INTERVAL '20 hours', 82);

-- Hyderabad News
INSERT INTO local_news (id, headline, url, source, snippet, is_tragic, city, location, published_at, confidence_score) VALUES
(gen_random_uuid(), 'Hyderabad Metro Rail extends services to Shamshabad Airport', 'https://example.com/hyderabad-metro-airport', 'Deccan Chronicle', 'L&T Metro Rail completes 31km Airport Line connecting Raidurg to RGIA', false, 'hyderabad', ST_SetSRID(ST_MakePoint(78.4867, 17.3850), 4326), NOW() - INTERVAL '5 hours', 89),
(gen_random_uuid(), 'GHMC demolishes 23 illegal structures in Kukatpally', 'https://example.com/ghmc-demolition', 'Telangana Today', 'Civic body takes action against unauthorized constructions violating building regulations', true, 'hyderabad', ST_SetSRID(ST_MakePoint(78.4089, 17.4849), 4326), NOW() - INTERVAL '9 hours', 74),
(gen_random_uuid(), 'ORR Phase 2 work progresses with 8 new flyovers', 'https://example.com/hyderabad-orr-phase2', 'Times of India', 'HMDA reports 70% completion of Outer Ring Road expansion project worth Rs 3,500 crore', false, 'hyderabad', ST_SetSRID(ST_MakePoint(78.5569, 17.4399), 4326), NOW() - INTERVAL '13 hours', 85),
(gen_random_uuid(), 'Hussain Sagar lake pollution levels exceed permissible limits', 'https://example.com/hussain-sagar-pollution', 'The Hindu', 'TSPCB study reveals high levels of industrial effluents affecting water quality', true, 'hyderabad', ST_SetSRID(ST_MakePoint(78.4744, 17.4239), 4326), NOW() - INTERVAL '17 hours', 78);

-- Chennai News
INSERT INTO local_news (id, headline, url, source, snippet, is_tragic, city, location, published_at, confidence_score) VALUES
(gen_random_uuid(), 'Chennai Metro Phase 2 begins trial runs on Madhavaram-SIPCOT corridor', 'https://example.com/chennai-metro-phase2', 'The Hindu', 'CMRL announces commercial operations to start from next month on 118km extended network', false, 'chennai', ST_SetSRID(ST_MakePoint(80.2707, 13.0827), 4326), NOW() - INTERVAL '6 hours', 86),
(gen_random_uuid(), 'Adyar river encroachments: Corporation identifies 340 structures', 'https://example.com/adyar-encroachment', 'Times of India', 'GCC prepares eviction plan for illegal constructions along 42km river stretch', true, 'chennai', ST_SetSRID(ST_MakePoint(80.2574, 13.0067), 4326), NOW() - INTERVAL '10 hours', 80),
(gen_random_uuid(), 'Elevated corridor from Maduravoyal to Tambaram gets approval', 'https://example.com/chennai-elevated-corridor', 'Deccan Chronicle', 'State government sanctions Rs 6,200 crore project to ease traffic congestion on GST Road', false, 'chennai', ST_SetSRID(ST_MakePoint(80.1300, 12.9249), 4326), NOW() - INTERVAL '14 hours', 83),
(gen_random_uuid(), 'Cyclone warning: Low-lying areas in North Chennai evacuated', 'https://example.com/chennai-cyclone-warning', 'Indian Express', 'District administration relocates 2,500 families from coastal areas to relief camps', true, 'chennai', ST_SetSRID(ST_MakePoint(80.2785, 13.1067), 4326), NOW() - INTERVAL '19 hours', 77);

-- Kolkata News
INSERT INTO local_news (id, headline, url, source, snippet, is_tragic, city, location, published_at, confidence_score) VALUES
(gen_random_uuid(), 'Kolkata Metro extends Purple Line to Joka with 6 new stations', 'https://example.com/kolkata-metro-joka', 'Telegraph India', 'Metro Railway completes 16.5km extension connecting South Kolkata to Joka', false, 'kolkata', ST_SetSRID(ST_MakePoint(88.3639, 22.5726), 4326), NOW() - INTERVAL '7 hours', 84),
(gen_random_uuid(), 'KMC identifies 89 buildings at risk of collapse in monsoon', 'https://example.com/kolkata-building-risk', 'Times of India', 'Municipal corporation issues notices to owners of century-old structures in North Kolkata', true, 'kolkata', ST_SetSRID(ST_MakePoint(88.3639, 22.5958), 4326), NOW() - INTERVAL '11 hours', 79),
(gen_random_uuid(), 'New Town smart city project completes Phase 3 infrastructure', 'https://example.com/newtown-smart-city', 'Economic Times', 'HIDCO develops 2,500 acres with integrated utilities and green spaces', false, 'kolkata', ST_SetSRID(ST_MakePoint(88.4615, 22.5958), 4326), NOW() - INTERVAL '16 hours', 81),
(gen_random_uuid(), 'Hooghly river water quality deteriorates in industrial belt', 'https://example.com/hooghly-pollution', 'The Hindu', 'WBPCB reports high levels of chemical pollutants affecting drinking water supply', true, 'kolkata', ST_SetSRID(ST_MakePoint(88.3476, 22.5744), 4326), NOW() - INTERVAL '21 hours', 75);
